### ISSUE TITLE
https://github.com/40fingers/Dnn-Google-Tag-Manager-Connector/blob/master/_install/GoogleTagManagerConnector_09.07.02_Install.zip

### ISSUE THREAD

**Issue by arzpgh60** [40fingers/Dnn-Google-Tag-Manager-Connector#3]

**Comment by skamphuis** [comment]
I don't know what your issue is, but this project is already included in DNN Platform itself and is supported [there](https://github.com/dnnsoftware/Dnn.Platform).

Thanks.
